services:
  front-end:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    env_file:
      - path: ./.env
        required: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${PORT}:${PORT}"
