name: Front End Workflows

on:
  push:
    branches:
      - "**"
    paths:
      - "front-end/**"

defaults:
  run:
    working-directory: ./front-end

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: front-end/package.json

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: front-end/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: npm run build
